
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archive-analyzer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: archive-analyzer
  template:
    metadata:
      labels:
        app: archive-analyzer
    spec:
      containers:
      - name: archive-analyzer
        image: gcr.io/YOUR_PROJECT_ID/archive-analyzer:latest
        ports:
        - containerPort: 7860
