
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cybersecurity-framework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cybersecurity
  template:
    metadata:
      labels:
        app: cybersecurity
    spec:
      containers:
      - name: app
        image: cybersecurity/framework:latest
        ports:
        - containerPort: 5000
