# app/intelligence/src/analytics/real_time_engine.py

from typing import Dict, List, Optional
import asyncio
import numpy as np
from datetime import datetime
import pandas as pd

class RealTimeAnalyticsEngine:
    def __init__(self):
            self.data_streams = {}
                    self.analytics_queue = asyncio.Queue()
                            self.alert_threshold = 0.75
                                    
                                        async def process_stream(self, stream_id: str, data: Dict):
                                                """Process incoming data stream in real-time"""
                                                        try:
                                                                    # Add timestamp
                                                                                data['timestamp'] = datetime.utcnow()
                                                                                            
                                                                                                        # Add to stream buffer
                                                                                                                    if stream_id not in self.data_streams:
                                                                                                                                    self.data_streams[stream_id] = []
                                                                                                                                                self.data_streams[stream_id].append(data)
                                                                                                                                                            
                                                                                                                                                                        # Trigger analysis
                                                                                                                                                                                    await self.analytics_queue.put({
                                                                                                                                                                                                        'stream_id': stream_id,
                                                                                                                                                                                                                        'data': data
                                                                                                                                                                                    })
                                                                                                                                                                                                
                                                                                                                                                                                                            # Process analytics queue
                                                                                                                                                                                                                        await self.process_analytics_queue()
                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                            except Exception as e:
                                                                                                                                                                                                                                                        raise Exception(f"Stream processing failed: {str(e)}")

                                                                                                                                                                                                                                                            async def process_analytics_queue(self):
                                                                                                                                                                                                                                                                    """Process queued analytics tasks"""
                                                                                                                                                                                                                                                                            while not self.analytics_queue.empty():
                                                                                                                                                                                                                                                                                        item = await self.analytics_queue.get()
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                # Perform real-time analysis
                                                                                                                                                                                                                                                                                                                            analysis_result = await self.analyze_data(
                                                                                                                                                                                                                                                                                                                                                item['stream_id'],
                                                                                                                                                                                                                                                                                                                                                                item['data']
                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                    # Check for alerts
                                                                                                                                                                                                                                                                                                                                                                if analysis_result['threat_score'] > self.alert_threshold:
                                                                                                                                                                                                                                                                                                                                                                                await self.generate_alert(analysis_result)

                                                                                                                                                                                                                                                                                                                                                                                    async def analyze_data(self, stream_id: str, data: Dict) -> Dict:
                                                                                                                                                                                                                                                                                                                                                                                            """Perform real-time data analysis"""
                                                                                                                                                                                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                                                                                                                                                                                # Get historical data for context
                                                                                                                                                                                                                                                                                                                                                                                                                            history = self.data_streams[stream_id][-100:]  # Last 100 entries
                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Calculate metrics
                                                                                                                                                                                                                                                                                                                                                                                                                                                                metrics = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'volume': len(history),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'frequency': self.calculate_frequency(history),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'pattern_score': self.detect_patterns(history),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'anomaly_score': self.detect_anomalies(data, history)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Calculate threat score
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    threat_score = self.calculate_threat_score(metrics)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'stream_id': stream_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'timestamp': datetime.utcnow(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'metrics': metrics,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'threat_score': threat_score,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'raw_data': data
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            raise Exception(f"Data analysis failed: {str(e)}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                    })